refactor: add fields and refactor initialization
thiagotnunes/beam pull request #11
Opened 2021-06-10 06:39 UTC by zoercai

2021-06-10 06:42 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          .replaceAll("-", "_");
Considered making a name generator class but it's just one line so seemed a bit silly, if we have other names to generate in the future we should make a class

2021-06-10 08:50 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/PipelineInitializer.java
> +            + COLUMN_PARENT_TOKEN + " ARRAY<STRING(MAX)> NOT NULL,"
Another error when I run the IT with this DDL: 

```
com.google.cloud.spanner.SpannerException: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Error parsing Spanner DDL statement: CREATE T
ABLE CDC_Partitions_beam_testdb_5704603c_8697_4372_93d8_b3195636fd7d (PartitionToken STRING(MAX) NOT NULL,ParentToken ARRAY<STRING(MAX)> NOT NULL,StartTimestamp
 TIMESTAMP NOT NULL,InclusiveStart BOOL NOT NULL, EndTimestamp TIMESTAMP,InclusiveEnd BOOL,HeartbeatSeconds INT64 NOT NULL,State STRING(MAX) NOT NULL,CreatedAt
TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),UpdatedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (PartitionToken); : Syn
tax error on line 1, column 482: Expecting 'EOF' but found an unknown character (';').
```

`;` on Line 74 is not needed and should be removed.

2021-06-15 09:01 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTestUtils.java
> +    return databaseIdPrefix + "-" + random;
Shouldn't we use `_` instead of `-` here? I thought `-` would error out.

2021-06-16 01:23 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/PipelineInitializer.java
> +  public static void initialize(DatabaseAdminClient databaseAdminClient,
Mostly because the methods in here don't rely on state, and I don't see us needing to create different/multiple instances of this class especially considering the parameters passed into `initialize()` determine pretty much everything we might want to customise with the methods behaviour. But if we do end up adding state to the class I'm happy to change it to non-static which should be a very easy change

2021-06-16 01:24 UTC, zoercai commented on sdks/java/io/google-cloud-platform/build.gradle
> +  include '**/**/*IT.class'
Ah I will remove this, thanks!

2021-06-16 01:27 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerTestUtils.java
> +    return databaseIdPrefix + "-" + random;
This is for the database name rather than the table name so `-` is fine. I actually copied this from refactoring the other existing Spanner test classes so probably shouldn't change it

![image](https://user-images.githubusercontent.com/8233863/122143872-ae9e7000-ce95-11eb-99fc-939d92063eeb.png)

2021-06-16 01:28 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          .replaceAll("-", "_");
Yep you're right I should be testing this method, will move it out and add a test

2021-06-16 01:50 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          .replaceAll("-", "_");
I will forgo the check for the database ID though, since spannerIO already checks that the database exists before getting to this, and doesn't seem like the responsibility of the name generator to query spanner and check the db exists

2021-06-16 06:02 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/build.gradle
> +  def gcpSpannerInstance = project.findProperty('gcpSpannerInstance') ?: 'beam-test-instance'
We should not change this task because this is very special for kms. I have updated the `integrationTest` task instead of this one.

2021-06-16 06:05 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          !getInclusiveStartAt().toSqlTimestamp().before(earliestVersionTime.toSqlTimestamp()));
I think we should remove this check. `earliestVersionTime` is not relevant for change stream. We need to find out the `retention period` of a change stream. I think they are two different concepts. We need to check with the backend team.

2021-06-16 06:05 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          "Start time must not be before the change stream database creation time.");
Same here. This check is not necessary.

2021-06-16 06:10 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/model/ColumnType.java
> +import com.google.common.base.Objects;
please run `./gradlew :sdks:java:io:google-cloud-platform:build` to fix this import.

2021-06-16 06:11 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/model/ColumnType.java
> +  private long ordinalPosition;
Just curious: what is the purpose of this param?

2021-06-16 06:15 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/SpannerReadIT.java
> +import org.apache.beam.sdk.io.gcp.spanner.SpannerTestUtils.SpannerTestPipelineOptions;
I would suggest to not change these two test files: SpannerReadIT.java and SpannerWriteIT.java.

2021-06-16 06:23 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/cdc/PipelineInitializerIT.java
> +public class PipelineInitializerIT {
We don't need `PipelineInitializerIT`. As you said, if we treat the entire pipeline as a blackbox, the user wouldn't know `PipelineInitializer` exists because this is not how users will use our Connector. Please check `SpannerChangeStreamIT.java` (this is only one we need) in my PR and also refer to `SpannerReadIT.java`, `SpannerWriteIT.java` and [KafkaIOIT.java]https://github.com/apache/beam/blob/acc0f76a2f3292276ae144f84c4130c504a334a1/sdks/java/io/kafka/src/test/java/org/apache/beam/sdk/io/kafka/KafkaIOIT.java.

2021-06-16 06:25 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner/cdc/PipelineInitializerIT.java
> +public class PipelineInitializerIT {
If you check this directory (https://github.com/thiagotnunes/beam/tree/d868bc9888db4ccbfa2cbeae80b2ce67b3509ee5/sdks/java/io/google-cloud-platform/src/test/java/org/apache/beam/sdk/io/gcp/spanner), you will know that there are not ITs for internal components.

2021-06-16 06:27 UTC, hengfengli requested changes
Generally, looks good to me. The major issue is that `PipelineInitializerIT.java` is not needed and I prefer to not touch `SpannerReadIT.java` and `SpannerWriteIT.java`.

2021-06-17 04:54 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +          !getInclusiveStartAt().toSqlTimestamp().before(earliestVersionTime.toSqlTimestamp()));
I've removed the version time check as well as the start timestamp < db creation time check

2021-06-17 06:54 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/model/ColumnType.java
> +  private long ordinalPosition;
This is the position of the column, it's in the design doc but tbh I'm not sure why we need this considering we have the column name already, unless there's some performance disadvantage or feature that we're missing out on from not using the ordinal position? @thiagotnunes do we need this?

2021-06-17 08:55 UTC, thiagotnunes approved these changes

2021-06-17 08:55 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/model/ColumnType.java
> +  private long ordinalPosition;
We need to send this alongside the data change stream record, since it is defined by the API. We (the Connector), won't use it for anything.

2021-06-17 12:33 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/TimestampEncoding.java
> +    final long seconds =in.readLong();
nits: Interesting. Why does it remove the white space?

2021-06-17 12:34 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/build.gradle
> +  def gcpSpannerInstance = project.findProperty('gcpSpannerInstance') ?: 'beam-test-instance'
It doesn't need to change in this PR, although I have updated it in my PR.

2021-06-17 12:35 UTC, hengfengli approved these changes
LGTM.

2021-06-18 01:53 UTC, zoercai commented on sdks/java/io/google-cloud-platform/build.gradle
> +  def gcpSpannerInstance = project.findProperty('gcpSpannerInstance') ?: 'beam-test-instance'
I've removed this

2021-06-18 02:05 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/TimestampEncoding.java
> +    final long seconds =in.readLong();
Good spotting! And yeah weird, I ran lint right before pushing too, maybe I accidentally pressed the backspace while committing. It's fixed now though

2021-06-18 02:06 UTC, merged