Add dao methods & ran checkstyle
thiagotnunes/beam pull request #14
Opened 2021-06-17 08:31 UTC by zoercai

2021-06-17 08:38 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
>        final DaoFactory daoFactory = new DaoFactory(getChangeStreamName());
this creates a PartitionMetadataDao, which has already been created on line 1413

2021-06-17 08:39 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +/*
Most of the changes are in here!

2021-06-17 09:06 UTC, thiagotnunes requested changes
Requesting changes just because of the ResultSet outside of the `try with resources` block.

Could you run some manual (integration) testing before merging this? I am wondering if some of the queries will not work (per comments below), but I might be wrong.

2021-06-17 09:06 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +            .toStringArray(states.stream().map(Enum::toString).collect(Collectors.toList()))
Does this work without an `UNNEST`?

2021-06-17 09:06 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +            .bind("table")
Same as question as above

2021-06-17 09:06 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +              final InTransactionContext dao = new InTransactionContext(tableName, transaction);
nit: Sorry, I thing I misnamed this variable, could we change it to something like `transactionContext`?

2021-06-17 09:06 UTC, thiagotnunes commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +      final ResultSet resultSet =
This `ResultSet resultSet` should be in a `try with resources` block

2021-06-18 06:43 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +            .bind("table")
Tested it out and no 😞 I've changed these to use string concat

2021-06-18 07:16 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/cdc/dao/PartitionMetadataDao.java
> +/*
have removed the checkstyle changes

2021-06-18 07:16 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
>        final DaoFactory daoFactory = new DaoFactory(getChangeStreamName());
added a todo

2021-06-18 11:01 UTC, thiagotnunes approved these changes

2021-06-18 11:02 UTC, merged