feat: add metadata table cleanup
thiagotnunes/beam pull request #52
Opened 2021-08-12 09:26 UTC by zoercai

2021-08-12 13:20 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +            .apply(Wait.on(results))
If I cancel a running pipeline, would it also clean up the metadata table?

2021-08-12 13:24 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +            .apply(Wait.on(results))
Where is this `Wait` symbol from? I couldn't see any import for `Wait`.

2021-08-12 13:47 UTC, hengfengli approved these changes
LGTM.

2021-08-12 13:55 UTC, hengfengli commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +            .apply(Wait.on(results))
From my understanding, it should look like this: 

```
PCollection<byte[]> impulseOut = p.apply(Impulse.create());

PCollection<DataChangeRecord> results =
    impulseOut
        .apply("Generate change stream sources", Create.of(sources))       // This step needs to be updated. 
        .apply("Detect new partitions", ParDo.of(detectNewPartitionsDoFn))
        .apply("Read change stream partition", ParDo.of(readChangeStreamPartitionDoFn))
        .apply("Post processing metrics", ParDo.of(postProcessingMetricsDoFn));

impulseOut
        .apply(Wait.on(results))
        .apply(ParDo.of(new CleanUpReadChangeStreamDoFn(daoFactory)));
```

2021-08-12 13:56 UTC, hengfengli requested changes
Sorry, I gave it a second thought and think the use of `Impulse.create()` may need to be changed. Probably need to check it with Luke.

2021-08-12 23:31 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +            .apply(Wait.on(results))
> If I cancel a running pipeline, would it also clean up the metadata table?

Luke said the only way for the table to be cleaned up if the pipeline is interrupted is to use Spanner TTL

2021-08-12 23:35 UTC, zoercai commented on sdks/java/io/google-cloud-platform/src/main/java/org/apache/beam/sdk/io/gcp/spanner/SpannerIO.java
> +            .apply(Wait.on(results))
> Where is this Wait symbol from? I couldn't see any import for Wait.

It's on line 87, already imported: https://github.com/thiagotnunes/beam/pull/52/files#diff-12d8841cc4fa9802d7b0640b8354aee6d668a2f92fad6491901a216f92cd2ee8R87

2021-08-13 00:22 UTC, hengfengli approved these changes
Thanks for the change. LGTM.

2021-08-13 00:24 UTC, merged